"""Stage A1 audit -- FND-CLIP Real-vs-OOC binary capability check (P14.A1).

Question this answers:
  Is the 5-class downstream F1 ceiling of ~0.42 on classes 0/1 caused by
  FND-CLIP itself being unable to separate Real vs OOC, or by the fusion
  module diluting a perfectly-good FND-CLIP signal?

Method:
  1. Load cached v_semantic [512-d] vectors for classes 0+1 rows of
     forensic_5class_unified_blip2.csv.
  2. Train a LogisticRegression on train+val rows.
  3. Evaluate on test rows.
  4. Report acc, F1, AUC, confusion matrix.

If acc > 0.75 -> FND-CLIP separates them well; fusion is the bottleneck.
If acc < 0.60 -> FND-CLIP is the bottleneck; full architecture is data-limited.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (accuracy_score, classification_report,
                             confusion_matrix, f1_score, roc_auc_score)


def load_cached_v_semantic(sample_ids, cache_root: Path) -> np.ndarray:
    vecs = []
    missing = 0
    for sid in sample_ids:
        p = cache_root / f"{sid}.pt"
        if not p.exists():
            missing += 1
            vecs.append(np.zeros(512, dtype=np.float32))
            continue
        t = torch.load(p, map_location="cpu", weights_only=True)
        if isinstance(t, dict):
            t = t.get("feature", next(iter(t.values())))
        vecs.append(t.cpu().numpy().astype(np.float32).flatten())
    if missing:
        print(f"  WARN: {missing}/{len(sample_ids)} cache shards missing (zero-filled)")
    return np.stack(vecs, axis=0)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--manifest", type=Path,
                   default=Path("data/processed/forensic_5class_unified_blip2.csv"))
    p.add_argument("--cache-root", type=Path,
                   default=Path("cache/v3/_features/v_semantic"))
    p.add_argument("--out", type=Path, default=Path("docs/FNDCLIP_REAL_OOC_AUDIT.md"))
    args = p.parse_args()

    df = pd.read_csv(args.manifest)
    bin_df = df[df["label"].isin([0, 1])].copy()
    print(f"[A1] manifest: {len(df)} rows, binary OOC subset: {len(bin_df)} rows")

    splits = {s: bin_df[bin_df["split"] == s] for s in ("train", "val", "test")}
    for s, sdf in splits.items():
        balance = sdf["label"].value_counts().to_dict()
        print(f"  split={s}: n={len(sdf)} (cls0={balance.get(0,0)}, cls1={balance.get(1,0)})")

    print("[A1] loading cached v_semantic vectors ...")
    X_train = load_cached_v_semantic(splits["train"]["sample_id"], args.cache_root)
    X_val = load_cached_v_semantic(splits["val"]["sample_id"], args.cache_root)
    X_test = load_cached_v_semantic(splits["test"]["sample_id"], args.cache_root)
    y_train = splits["train"]["label"].values
    y_val = splits["val"]["label"].values
    y_test = splits["test"]["label"].values
    print(f"  shapes: X_train={X_train.shape}, X_val={X_val.shape}, X_test={X_test.shape}")

    X_fit = np.concatenate([X_train, X_val], axis=0)
    y_fit = np.concatenate([y_train, y_val], axis=0)
    print("[A1] training LogisticRegression on train+val (n=%d) ..." % len(X_fit))
    clf = LogisticRegression(max_iter=2000, C=1.0, random_state=42)
    clf.fit(X_fit, y_fit)

    y_pred = clf.predict(X_test)
    y_proba = clf.predict_proba(X_test)[:, 1]
    acc = float(accuracy_score(y_test, y_pred))
    f1 = float(f1_score(y_test, y_pred))
    auc = float(roc_auc_score(y_test, y_proba))
    cm = confusion_matrix(y_test, y_pred).tolist()

    print(f"\n[A1] test results:")
    print(f"  accuracy: {acc:.4f}")
    print(f"  F1 (cls 1 OOC): {f1:.4f}")
    print(f"  AUC: {auc:.4f}")
    print(f"  confusion matrix [TN, FP / FN, TP]: {cm}")
    print()
    print(classification_report(y_test, y_pred, target_names=["Real (0)", "OOC (1)"]))

    if acc > 0.75:
        verdict = "FND-CLIP CAN separate Real vs OOC linearly. The 5-class downstream F1 ceiling (~0.42) is caused by the FUSION module, not FND-CLIP."
    elif acc > 0.60:
        verdict = "FND-CLIP partially separates Real vs OOC. Both FND-CLIP and fusion contribute to the ceiling."
    else:
        verdict = "FND-CLIP CANNOT separate Real vs OOC linearly. The 5-class downstream F1 ceiling is fundamental to FND-CLIP, not the fusion module. Data-scale limit."

    lines = [
        "# FND-CLIP Real-vs-OOC audit (Stage A1)",
        "",
        "> Generated by `phases/v4/scripts/audit_fndclip_real_ooc.py`.",
        "",
        "## Question",
        "",
        "Is the 5-class downstream F1 ceiling on classes 0/1 (~0.397 / 0.442 in the",
        "honest-path ensemble) caused by **FND-CLIP itself** failing to separate Real",
        "vs OOC, or by the **fusion module** diluting an otherwise-good FND-CLIP signal?",
        "",
        "## Method",
        "",
        "Trained a `LogisticRegression(max_iter=2000, C=1.0, random_state=42)` on the",
        "cached `v_semantic` 512-d FND-CLIP V1 vectors for classes 0+1 (binary OOC):",
        "",
        f"- Train+val (fit set): n={len(X_fit)}",
        f"- Test (held-out): n={len(X_test)}",
        "- FND-CLIP ckpt: V1 leakfree (`outputs/v1/leakfree/best.pt`)",
        f"- Cache: `{args.cache_root}` (512-d)",
        "",
        "## Test metrics",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| Accuracy | **{acc:.4f}** |",
        f"| F1 (OOC class) | **{f1:.4f}** |",
        f"| AUC | **{auc:.4f}** |",
        f"| Confusion matrix `[[TN, FP], [FN, TP]]` | `{cm}` |",
        "",
        "## Classification report",
        "",
        "```",
        classification_report(y_test, y_pred, target_names=["Real (0)", "OOC (1)"]),
        "```",
        "",
        "## Verdict",
        "",
        f"**{verdict}**",
        "",
        "## Cross-reference with downstream 5-class numbers",
        "",
        "| Source | Class 0 (Real) F1 | Class 1 (OOC) F1 |",
        "|---|---|---|",
        "| Honest-path 3-seed ensemble (full pipeline) | 0.397 | 0.442 |",
        f"| FND-CLIP linear probe accuracy on binary OOC | {acc:.3f} | (single binary number) |",
        "",
        "If linear-probe accuracy is **higher** than downstream F1, fusion is losing",
        "information. If it's **at or below** downstream F1, FND-CLIP is the floor and",
        "the fusion module is roughly as good as it can be given this encoder.",
        "",
        "## Provenance",
        "",
        f"- Manifest: `{args.manifest}` ({len(df)} rows, {len(bin_df)} binary OOC rows)",
        f"- v_semantic cache: `{args.cache_root}`",
        "- Computed using sklearn 1.x LogisticRegression on raw 512-d vectors (no scaling, no PCA).",
    ]

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines), encoding="utf-8")
    print(f"\n[A1] wrote {args.out}")

    return {"accuracy": acc, "f1": f1, "auc": auc, "confusion_matrix": cm, "verdict": verdict}


if __name__ == "__main__":
    result = main()
    print(json.dumps(result, indent=2))
